### ISSUE TITLE
Several traits not activated at 1.16

### ISSUE THREAD

**Issue by HauserGrim** [Nathat23/StackMob-5#216]
https://github.com/Nathat23/StackMob-5/blob/master/src/main/java/uk/antiperson/stackmob/entity/traits/TraitManager.java#L41
If version not 1.15, traits bellow not be activated.
Maybe you should think about new check?

**Comment by Nathat23** [comment]
Zoglins and piglins are not in 1.15. The turtle check could be moved as those do exist in 1.15.

**Comment by Nathat23** [comment]
fixed in 37ea89c052fe5fb04709e80fa4473af0b296b5c7

**Comment by HauserGrim** [comment]
Not fixed, isNewBukkit() method checks for 1.15
"if (!1.15) { return; }" - traits for piglins / zoglins will not work in 1.16

**Comment by Nathat23** [comment]
Oh yeah. Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
