### ISSUE TITLE
Console commands are broken.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#260]
Paper 1.19.2 Build 132
StackMob Latest (Built upon https://github.com/Nathat23/StackMob-5/commit/d80e7c15057bdb2bd59e9d6d113639bf6beffe58)

Testing all three commands:
/sm forcestack
/sm forcestack named
/sm forcestack tamed
https://pastebin.com/raw/nRERW1YF

**Comment by andrewkm** [comment]
Now that I look at it, it looks like no commands work at all @Nathat23 (in console).
Meanwhile in game they work fine.

**Comment by Nathat23** [comment]
Should be fixed in above commit

**Comment by andrewkm** [comment]
@Nathat23 Unfortunately errors persist.

https://gist.githubusercontent.com/andrewkm/be381e9d3e4166a68fb71127b73dd04c/raw/a9d0d35a8661793118334a759bae33c9f9d06b5f/gistfile1.txt

**Comment by Nathat23** [comment]
Oops. Try again now.
